
//Authentication
export const LOGIN_USER="LOGIN_USER"
export const LOGOUT_USER="LOGOUT_USER"

//Products
export const GET_ALL_PRODUCTS="GET_ALL_PRODUCTS"
export const GET_PRODUCTS_DETAILS="GET_PRODUCTS_DETAILS"
export const UPDATE_PRODUCT="UPDATE_PRODUCT"
export const DELETE_INSTRUCTION="DELETE_INSTRUCTION"

//Customers || users
export const GET_ALL_USERS="GET_ALL_USERS"
export const GET_USER_DETAILS="GET_USER_DETAILS"
export const UPDATE_USER="UPDATE_USER"
export const UPDATE_USER_STATUS="UPDATE_USER_STATUS"
export const UPDATE_USER_SEGMENT="UPDATE_USER_SEGMENT"
export const CREATE_USER="CREATE_USER"
export const DELETE_USER="DELETE_USER"

//Admins
export const GET_ALL_ADMINS="GET_ALL_ADMINS"
export const GET_ADMIN_DETAILS="GET_ADMIN_DETAILS"
export const UPDATE_ADMIN="UPDATE_ADMIN"
export const CREATE_ADMIN="CREATE_ADMIN"
export const DELETE_ADMIN="DELETE_ADMIN"

//Roles
export const GET_ALL_ROLES="GET_ALL_ROLES"
export const SHOW_ROLE="EDIT_ROLE"
export const CREATE_ROLE="CREATE_ROLE"
export const UPDATE_ROLE="UPDATE_ROLE"
export const DELETE_ROLE="DELETE_ROLE"

//Permission
export const GET_ALL_PERMISSION="GET_ALL_PERMISSION"
export const SHOW_PERMISSION="EDIT_PERMISSION"
export const CREATE_PERMISSION="CREATE_PERMISSION"
export const UPDATE_PERMISSION="UPDATE_PERMISSION"
export const DELETE_PERMISSION="DELETE_PERMISSION"


//invoices
export const GET_INVOICES_COUNT="GET_INVOICES_COUNT"
export const GET_ALL_INVOICES="GET_ALL_INVOICES"
export const GET_FILTER_INVOICES="GET_FILTER_INVOICES"
export const UPDATE_INVOICE="UPDATE_INVOICE"

//Segments
export const GET_ALL_SEGMENTS="GET_ALL_SEGMENTS"
export const GET_SEGMENT_DETAILS="GET_SEGMENT_DETAILS"
export const CREATE_SEGMENT="CREATE_SEGMENT"
export const DELETE_SEGMENT="DELETE_SEGMENT"
export const UPDATE_SEGMENT="UPDATE_SEGMENT"

//Dashboard
export const GET_STORES_CHARTS="GET_STORES_CHARTS"
export const GET_STOCK_CHARTS="GET_STOCK_CHARTS"
export const GET_INVOICES_AVG="GET_INVOICES_AVG"
export const GET_INVOICES_MAP="GET_INVOICES_MAP"

//Categories
export const GET_ALL_CATEGORIES="GET_ALL_CATEGORIES"
export const GET_CATEGORY_DETAILS="GET_CATEGORY_DETAILS"
export const CREATE_CATEGORY="CREATE_CATEGORY"
export const UPDATE_CATEGORY="UPDATE_CATEGORY"

//OSA Barcode
export const GET_ALL_BARCODES="GET_ALL_BARCODES"
export const GET_BARCODE_DETAILS="GET_BARCODE_DETAILS"
export const STORE_BARCODE="STORE_BARCODE"
export const UPDATE_BARCODE="UPDATE_BARCODE"
export const DELETE_BARCODE="DELETE_BARCODE"

//Import
export const POST_CUSTOMER="POST_CUSTOMER"
export const POST_PRODUCT="POST_PRODUCT"
export const POST_CATEGORY="POST_CATEGORY"
export const POST_BARCODE="POST_BARCODE"






