
//Authentication
export const LOGIN_USER="LOGIN_USER"
export const LOGOUT_USER="LOGOUT_USER"

//Products
export const GET_ALL_PRODUCTS="GET_ALL_PRODUCTS"
export const GET_PRODUCTS_DETAILS="GET_PRODUCTS_DETAILS"
export const UPDATE_PRODUCT="UPDATE_PRODUCT"
export const DELETE_INSTRUCTION="DELETE_INSTRUCTION"

//Customers || users
export const GET_ALL_USERS="GET_ALL_USERS"
export const GET_USER_DETAILS="GET_USER_DETAILS"
export const UPDATE_USER="UPDATE_USER"
export const UPDATE_USER_STATUS="UPDATE_USER_STATUS"
export const UPDATE_USER_SEGMENT="UPDATE_USER_SEGMENT"
export const CREATE_USER="CREATE_USER"
export const DELETE_USER="DELETE_USER"

//Admins
export const GET_ALL_ADMINS="GET_ALL_ADMINS"
export const GET_ADMIN_DETAILS="GET_ADMIN_DETAILS"
export const UPDATE_ADMIN="UPDATE_ADMIN"
export const CREATE_ADMIN="CREATE_ADMIN"
export const DELETE_ADMIN="DELETE_ADMIN"

//Roles
export const GET_ALL_ROLES="GET_ALL_ROLES"
export const SHOW_ROLE="EDIT_ROLE"
export const CREATE_ROLE="UPDATE_ADMIN"
export const UPDATE_ROLE="UPDATE_ADMIN"
export const DELETE_ROLE="DELETE_ADMIN"

//invoices
export const GET_INVOICES_COUNT="GET_INVOICES_COUNT"
export const GET_ALL_INVOICES="GET_ALL_INVOICES"
export const GET_FILTER_INVOICES="GET_ALL_INVOICES"

//Segments
export const GET_ALL_SEGMENTS="GET_ALL_SEGMENTS"
export const GET_SEGMENT_DETAILS="GET_SEGMENT_DETAILS"
export const CREATE_SEGMENT="CREATE_SEGMENT"
export const DELETE_SEGMENT="DELETE_SEGMENT"
export const UPDATE_SEGMENT="UPDATE_SEGMENT"

//Dashboard
export const GET_STORES_CHARTS="GET_STORES_CHARTS"
export const GET_STOCK_CHARTS="GET_STOCK_CHARTS"
export const GET_INVOICES_AVG="GET_INVOICES_AVG"
export const GET_INVOICES_MAP="GET_INVOICES_MAP"





